### ISSUE TITLE
Nice code

### ISSUE THREAD

**Issue by Kinzel** [RomanAbashin/rrenko#1]
Hello Roman, 

Studying your code I can see that you're very skilled in ggplot and data.table. I'm R developer as well and I have a renko code as well, and using some parts of your code I otimized my code (some parts) and build wonderful plots - I wasn't even close to plot this kind of renko, I was using lines.

I would like to know how we can help the community together in respect of renko in R. I think I have a very robust one. Can I change the codes here? Create a new one? I'm new in this platform.

**Comment by Kinzel** [comment]
I left the code at https://github.com/Kinzel/k_rrenko

See if you like

**Comment by rrmn** [comment]
Hey @Kinzel , thank you for the praise and sorry for the late reply. Wanna put our heads together to create something even better?
